### ISSUE TITLE
ECCV 2024 GalLoP

### ISSUE THREAD

**Issue by MarcLafon** [huytransformer/Awesome-Out-Of-Distribution-Detection#10]
Hi, Thank you for the awesome list of OOD papers!

Please also consider adding the recently published at ECCV2024 paper: "GalLoP: Learning Global and Local Prompts for Vision-Language Models" (https://arxiv.org/abs/2407.01400). 

It obtains the best OOD detection / accuracy tradeoff among prompt learning methods.

Best

Marc

**Comment by huytransformer** [comment]
Hi Marc,

Thanks for your suggestion. I will add it to the repo today. FYI you can always open a PR if you'd like to add any papers!

Best
Huy

**Comment by huytransformer** [comment]
The paper has been added. I'll close this issue for now.
